### ISSUE TITLE
[BUG] - Overflow on paths that are too long

### ISSUE THREAD

**Issue by RobertRR11** [Compliance-Resource-Pack/App#14]
**Describe the bug**
If the path of a texture is too long, the text and/or the delete and edit buttons overflow, which can also cause that buttons aren't visible at all.

Example texture: #1174 cartographer

**Screenshots**
![image](https://user-images.githubusercontent.com/57044042/147506820-4eb212d0-5346-4936-964e-943277668f29.png)
![image](https://user-images.githubusercontent.com/57044042/147506957-ae283706-51a1-4f81-b1e7-add7376dd28b.png)

**Comment by TheRolfFR** [comment]
Duplicate on #24, fixed with 75fa404e0e403d1a8607c60992bd7a06e90a64cf
