### ISSUE TITLE
[REQUEST] Use something other than a 32x32 checkerboard for transparent backgrounds in gallery

### ISSUE THREAD

**Issue by Pomi108** [Compliance-Resource-Pack/App#15]
Title says it all. Right now the transparency checkerboard in the gallery is 32x32, which makes textures like glass look really weird when viewed. 
![Snímek obrazovky 2021-12-31 v 13 38 25](https://user-images.githubusercontent.com/59484948/147823849-aafe6ad4-8176-4a04-8486-2a8fa88649ae.png)

Simply changing the checkerboard to a 2x2 or 4x4 one would do the trick in my opinion.

**Comment by HaragOnMC** [comment]
I agree. That's something developers should consider to change.
