### ISSUE TITLE
[BUG] - Non approved submissions can't be seen by owners

### ISSUE THREAD

**Issue by Juknum** [Compliance-Resource-Pack/App#29]
**Describe the bug**
When a user has submitted an add-on and goes back to its submissions page, the page doesn't load

**To Reproduce**
Steps to reproduce the behaviour:
1. Don't be an Admin (or someone who can see all non-approved addons)
2. Submit an add-on
3. Go back to the submissions page
4. See the error

**Expected behaviour**
Pending/Denied addons should still be accessible by owners

**Screenshots**
![image](https://user-images.githubusercontent.com/49886317/156689630-78498235-cd82-4499-bda2-0370054cf52b.png)
![image](https://user-images.githubusercontent.com/49886317/156689640-b533c3f2-9466-402b-8736-081c7e5f598f.png)

**Browser & Environment (computer/phone):**
 - Chrome & Mozilla (doesn't seems to be related)

**Additional context**
[code here](https://github.com/Compliance-Resource-Pack/App/blob/main/pages/addon/submissions.js#L127)

**Comment by TheRolfFR** [comment]
https://github.com/Compliance-Resource-Pack/API/commit/bd7dabce0833b9385265361d3b3c67eac5b1a54b fixed it
