### ISSUE TITLE
[BUG] - Cannot add additional images to a add-on that have been already approved.

### ISSUE THREAD

**Issue by HaragOnMC** [Compliance-Resource-Pack/App#3]
**Describe the bug**
When I try to add an additional image to my add-on, the site is showing during a frame of a second the image name but it removes it after. My image is 1920x1080, JPEG format.

**To Reproduce**
Steps to reproduce the behaviour:
1. Click on the edit button of your add-on. 
2. Click on'Replace additional image(s)
3. Chose your image.

**Expected behaviour**
Normally, the image name should stay where the button is.

**Screenshots**
Video available in Compliance Devs Discord in [#webapp](https://discord.com/channels/720677267424018526/881657754467577917/887281740845047839). (The image I used in this video was simply used as an example to show the bug. It does the same thing as for the image I said above.

**Browser & Environment (computer/phone):**
 - Firefox

**Logs**
If applicable, add screenshots of the console log (`ctrl` + `shift` + `i` for chrome/edge)

![image](https://user-images.githubusercontent.com/57374230/133298048-91a648c4-44d6-4e08-b306-07c4892186a3.png)

**Comment by Juknum** [comment]
Please give us information about the console log and the browser you're using.

**Comment by HaragOnMC** [comment]
> 
> 
> Please give us information about the console log and the browser you're using.

Firefox the browser and log gives nothing.

**Comment by Juknum** [comment]
Wontfix: because it would be automatically fixed in the new upcoming addon submission/edit system
