### ISSUE TITLE
[BUG] - White theme is mostly broken

### ISSUE THREAD

**Issue by Juknum** [Compliance-Resource-Pack/App#30]
**Describe the bug**
Some parts are still dark & the differences between elements are really bad :/

![image](https://user-images.githubusercontent.com/49886317/158706635-5411f472-686c-437f-9f25-c645a42a3a92.png)
![image](https://user-images.githubusercontent.com/49886317/158706684-bb2bcc5e-01bf-434c-b484-3304d18b8639.png)
![image](https://user-images.githubusercontent.com/49886317/158706727-f9101805-dda6-496e-b5ae-96e6dc0230ac.png)

**Browser & Environment (computer/phone):**
 - Edge

**Comment by TheRolfFR** [comment]
This is due to some cache problems, had to wait to solve them. I however did tweaked some things between commits 9a952e1c1737410358dfd41efb7cd3ed4db9fc0d...c5bfd142b71b8b0b211468be26b1c82cb2e6f8d8
