### ISSUE TITLE
[BUG] - 'dark' is not defined

### ISSUE THREAD

**Issue by Juknum** [Compliance-Resource-Pack/App#31]
**Describe the bug**
It seems that people that was logged in now gets the following errors when coming back to the webapp since the 'theme update' commit

**To Reproduce**
Steps to reproduce the behaviour:
1. Be already logged
2. Open the webapp
3. Nothing loads
4. See the error in the console

**Expected behaviour**
Not that lmao

**Screenshots**
![image](https://user-images.githubusercontent.com/49886317/158706961-70a72f84-007e-4627-81a6-065b954d75c9.png)

**Browser & Environment (computer/phone):**
 - Edge
 
 **Doing a hard refresh solve this issue**

**Comment by TheRolfFR** [comment]
Closed due to no further apparition
