### ISSUE TITLE
[BUG] - Unable to edit add-ons from other authors as admin

### ISSUE THREAD

**Issue by RobertRR11** [Compliance-Resource-Pack/App#32]
**Describe the bug**
As admin you are unable to edit an add-on from other authors, which has definitely worked before the add-on rework. You are able to open the edit page and make edits, but clicking the "submit" button does nothing.

**To Reproduce**
Steps to reproduce the behaviour:
1. Be an admin
2. Edit any add-on on the reviews page
3. Click submit

**Browser & Environment:**
- Brave 1.36.119 (based on Chromium 99.0.4844.83)

**Logs**
![image](https://user-images.githubusercontent.com/57044042/159720605-924ac3a6-65c7-4120-8503-00cd7ce27567.png)

**Comment by RobertRR11** [comment]
Addition: Looks like the add-on author itself also can't submit the edit and may likely be only on pending add-ons

**Comment by TheRolfFR** [comment]
Fixed with API commits [cdf57e..be4d728](https://github.com/Compliance-Resource-Pack/API/compare/cdf57e1ed471f2600a10b58ac9e45270f7bc8c49..be4d72881a335f8171242297845f25fe54157d59)
