### ISSUE TITLE
[FEATURE] - Add a way to edit/add/delete contribution directly on the webapp

### ISSUE THREAD

**Issue by Juknum** [Compliance-Resource-Pack/App#9]
**Is your feature request related to a problem? Please describe.**
As @Pomi108 said multiple times, you can't easily edit nor delete/add a contribution to a texture and fix missing/wrong contributions inside the database 

**Describe the solution you'd like**
If @Pomi108 can explain how she's seeing what she wants

**Describe alternatives you've considered**
_Smash my head on my keyboard to write code, jk._

**Additional context**
Nope

**Comment by Pomi108** [comment]
I'm just imagining some integration into the web app, like a button below every texture that opens a popup where i can modify the contribution info

**Comment by Juknum** [comment]
Implemented in [this commit](https://github.com/Compliance-Resource-Pack/App/commit/e33d44973b1423f258dbbc167b1e4b3717ffedec)
